### ISSUE TITLE
Proposal: extend createActionHelpers api

### ISSUE THREAD

**Issue by fxmaxvl** [f/vue-wait#21]
Hi, I have a proposal: add 2 action helpers - `mapActions` and `mapDecoratedActions`

https://gist.github.com/fxmaxvl/9353355f352561376812e90cff6a8a8b

**mapActions:** 
It just extends action's context and provides `$loading` property with `startLoading` and `endLoading` helpers.
It makes module's actions code cleaner and more testable.

**mapDecoratedActions:** 
It wraps action in try/finally block.
It can significantly reduce a boilerplate code with `startLoading` / `endLoading`.

**Comment by f** [comment]
Please review v1.0.0 PR that adds this feature.

**Comment by f** [comment]
Please upgrade to `"vue-wait": "^1.1.1"`
