### ISSUE TITLE
TypeError: this.$loading.init is not a function

### ISSUE THREAD

**Issue by 495640129** [f/vue-wait#24]
Here's my question:
TypeError: this.$loading.init is not a function

use:
"vue": "^2.5.9",
"vuex": "^3.0.1",
 "vuex-loading": "^0.2.6"

**Comment by mmieluch** [comment]
@495640129 You're probably using another package/framework that overrides `$loading` property on components.

Are you using Nuxt or VueElement package by any chance? These are the two I know suffer from name collision.

**Comment by f** [comment]
There's no method called `.init` in this framework. It's Vue's method.

**Comment by mmieluch** [comment]
@f This is the offending line:
https://github.com/f/vuex-loading/blob/d45d7fd2df6d9d751040947c14f9f83d2021d403/src/vuex-loading.js#L178

**Comment by mmieluch** [comment]
Just to make sure we're on the same page - I know you've introduced the change from `$loading` to `$vuexLoading` to avoid this common name collision. The problem reported in this issue should go away once you've pushed the updated package to NPM. Or @495640129 can install from the `master` branch on GitHub to get around the issue right now.

**Comment by f** [comment]
Wow

Sorry, you're right. I'm going to fix it ASAP.

**Comment by f** [comment]
Please upgrade to `"vue-wait": "^1.1.1"`
