### ISSUE TITLE
this.$vuexLoading.isLoading error Cannot read property 'isLoading' of undefined

### ISSUE THREAD

**Issue by d3bgger** [f/vue-wait#27]
version: 0.2.6

I've setup vuex-loading as described in the docs, with vuex support enabled. When i use this.$vuexLoading.isLoading from a component, i get 

TypeError: Cannot read property 'isLoading' of undefined

thanks in advance

**Comment by hi-zhaolei** [comment]
0.2.6 has bug in instaill method.

**Comment by f** [comment]
Please upgrade to `"vue-wait": "^1.1.1"`
