### ISSUE TITLE
Renaming the repo

### ISSUE THREAD

**Issue by f** [f/vue-wait#33]
Since `vuex-loading` is not really Vuex related now, we need a new name. `vue-loading` is registered.

Maybe we can find a fancier (hipster) name. Should we use `vue-` prefix?

**Comment by sky-code** [comment]
`vue-loading` sounds good for me

**Comment by f** [comment]
It's occupied on npm.

**Comment by sky-code** [comment]
`vuel` as have made `vuex` or to leave a project name as is

**Comment by f** [comment]
What about `vue-wait`?

**Comment by f** [comment]
I decided not to change it for now, if a brilliant idea comes, we can think about it. Also, renaming would cause some problems in future.

**Comment by f** [comment]
I asked npm if they can give me the name **vuel** and they did. I published the repo with `vuel` name, but I also liked `vue-wait`. On the other hand, **vuel** sounds more brand-ish.

I'm not sure but for next major version, maybe we can rename it too. Or maybe renaming a project twice is not a really good idea :)

However, we now have `vuel` name.

**Comment by sky-code** [comment]
`vuel` more brand-ish and more fancier (hipster) name, i don't think renaming project twice is a problem if renaming has occurred within a week.

**Comment by f** [comment]
`VueWait` -> `Vuel`
`$wait` -> `$vuel`

For `isWaiting` or `isLoading` what about just `is` since we already using `$vuel` prefix?

`$vuel.is("creating users")` sounds legit to me.

**Comment by f** [comment]
And we should think about `slot` name `waiting`. I think we should only rename `VueWait` to `Vuel` and let's leave rest as is.

**Comment by sky-code** [comment]
@f agree.
slot `waiting` can be renamed to `loading`

**Comment by f** [comment]
What about `is` to `waits`.

I wish we can use `?` as method name just like in Ruby.

**Comment by f** [comment]
This is the latest API proposal, let's discuss on it:

```
$vuel.start('creating user') # Starts a loader
$vuel.end('creating user') # Ends a loader
$vuel.waits('creating user') # Individual loading exists
$vuel.any # Any loading exists

# Template
<vuel for='creating user'>
  <template slot='loading'>Loading...</template>
</vuel>

# Mappers
...mapVuelGetters({...})
...mapVuelActions('module', {...})
```

| Current Keyword | Proposal |
| ------- | -------- |
| `$wait` | `$vuel` |
| `start` | `start` |
| `end` | `end` |
| `is` | `waits` |
| `any` | `any` |
| `<v-wait>` | `<vuel>` |
| `for=""` | `for=""` |
| `slot="waiting"` | `slot="loading"` |
| `mapWaitingGetters` | `mapVuelGetters` |
| `mapWaitingActions` | `mapVuelActions` |

Please share your own proposals.

**Comment by f** [comment]
Maybe @Koc also can share his opinions about it.

**Comment by sky-code** [comment]
or without `is` prefix

- `is`- `active`
- `any` - `activeAny` - or change semantic to check `any` if no args passed and remove this method

**Comment by f** [comment]
If we make `<vuel-wait>` or `<vuel-X>`, we should make slot name consistent to X.

```
<vuel-wait for="creating user">
  <template slot="waiting">Creating user, please wait...</template>
  User created.
</vuel-wait>
```

**Comment by Koc** [comment]
I'm prefer leave `$wait` is it possible and rename `is` to `waiting`: `$wait.waiting('product')`
