### ISSUE TITLE
Documentation: describe vuex getters

### ISSUE THREAD

**Issue by Koc** [f/vue-wait#38]
Documentation for vuex integration looks incomplete. Please show how to access vuex getters inside other getters. Like

```typescript
    [Getters.cartOperationsInProgress]: (state: CartState, getters, rootState, rootGetters): boolean => {
        console.log('cartOperationsInProgress');

        return rootGetters['wait/is']('cart.*');
    },
```

**Comment by f** [comment]
I would use `mapWaitingGetters` instead.

```js
import { mapWaitingGetters } from 'vue-wait'

export default {
  computed: {
    ...mapWaitingGetters({
      cartOperationsInProgress: 'cart.*'
    }),
  },
}
```

But for the more complex usages, we should add your example, too.

**Comment by f** [comment]
Done: https://github.com/f/vue-wait/commit/776a331041aa07dd975a69e19a325029f6f63ae5
