### ISSUE TITLE
dependency matcher causing UglifyJS Error

### ISSUE THREAD

**Issue by Ewocker** [f/vue-wait#42]
Using webpack3,
a package you use "matcher" cause: (I thought it was vue-wait but seems not)
```
ERROR in ... from UglifyJs
Unexpected character '`' ...
```

Not sure why it is like this, I had to put your package source as well as matcher in my source and transform with my babel setup. 

I was using this starting vuex-loading and it happens when I recently upgrade to this.
I think it is because matcher does not transform the code but I am not sure...
You might want to try it out yourself cuz this can make lots of frontend people move away from vue-wait which is a awesome package.

**Comment by f** [comment]
I bundled the matcher's code into the vue-wait. Please update to 1.2.3.

**Comment by Ewocker** [comment]
Thanks for the quick action bud!!!
I really enjoy using your tool.
