### ISSUE TITLE
Introduce ability to declare action by name from vuex module in mapWaitingActions when two actions in different modules has the same name

### ISSUE THREAD

**Issue by maciekkus** [f/vue-wait#50]
Hi,
Would this be possible to add support for different name for "waitingActions".
This could be useful especially when two actions has the same name in different modules.
Something like in the example code below.

    ...mapWaitingActions('vuex_module_name', {
      someActionFromModule: { waiter: 'this is waiter for someAction', action: 'actionName' } 
    }),

Kind regards,
Maciek

**Comment by maciekkus** [comment]
another use case:
using scenario described above I could dispatch the same action with different "waiters".

**Comment by f** [comment]
Wow this really makes sense.

**Comment by maciekkus** [comment]
@f here you can find PR: #55

**Comment by f** [comment]
#55 closes
