### ISSUE TITLE
FR: Usage with namespaced Vuex modules

### ISSUE THREAD

**Issue by razorfever** [f/vue-wait#53]
Splitting a Vuex store in one of my projects into namespaced modules made me think of the following.

Current way to use **vue-wait** with namespaced Vuex modules seems to be:
(Not documented btw.)

```javascript
import { mapWaitingActions } from 'vue-wait'

// ...
  methods: {
    ...mapWaitingActions('users', {
      'user/getUser': 'loading the user',
    }),
  },
  mounted() {
    // get the user data
    this.user = this['user/getUser'](this.userId);
  },
// ...
```

I think something like this would be more preferable:

```javascript
import { mapWaitingActions } from 'vue-wait'

// ...
  methods: {
    ...mapWaitingActions('users', {
      getUser: ['user/getUser', 'loading the user'],
    }),
  },
  mounted() {
    // get the user data
    this.user = this.getUser(this.userId);
  },
// ...
```

Thanks.

**Comment by f** [comment]
How your store looks like?

**Comment by f** [comment]
vue-wait already supports module namespaces. The first parameter is the namespace and it's optional.

**Comment by razorfever** [comment]
Oh sorry. It seems I made a copy / paste error while making the example and did not even spot the first parameter. I have tried to use it without it in my code like one would use the normal mapActions.

So what if I want to use actions from multiple modules?
Would this work:

```javascript
import { mapWaitingActions } from 'vue-wait'

// ...
  methods: {
    ...mapWaitingActions('users', {
      getUser: 'loading the user',
      updateUser: 'updating the user',
    }),
    ...mapWaitingActions('posts', {
      getPosts: 'loading the posts',
      deletePost: 'deleting a post',
    }),
  },
  mounted() {
    // get the user data
    this.user = this.getUser(this.userId);
    this.posts = this.getPosts(); 
  },
// ...

```

**Comment by f** [comment]
Sure this will work.

**Comment by razorfever** [comment]
Ok. Thanks. Sorry for the inconvenience. Keep up the good work
