### ISSUE TITLE
It does not work Internet Explorer 11

### ISSUE THREAD

**Issue by MustafaDal** [f/vue-wait#54]
This loader realy amazing and I'm happy to see made by a turkish people something open source.

when I use $wait.is('login'), error throw and everything stop working. Could you fix that, thanks.

[Vue warn]: Error in render: "TypeError: Object doesn't support property or method 'includes'"

**Comment by sky-code** [comment]
Hello, try to use polyfill
[google](https://www.google.com.ua/search?q=includes+polyfill&rlz=1C5CHFA_enUA728UA728&oq=includes+pol&aqs=chrome.1.69i57j0l5.5592j0j1&sourceid=chrome&ie=UTF-8)

**Comment by MustafaDal** [comment]
Hi, I am already using polyfill but it isn't working vue-wait

![includes-ss](https://user-images.githubusercontent.com/11693453/45152163-e6523680-b1d8-11e8-9f33-1745826a9f14.png)

**Comment by MustafaDal** [comment]
Just I changed webpack config and error gone, thanks for support.

from
```
entry: {
    polyfill: '@babel/polyfill',
    app: './src/main.js'
}
```
to
`entry: ['@babel/polyfill', './src/main.js']`
