### ISSUE TITLE
There are two v1.4.6 version in the release page, and the last v1.4.6 is not published to npm 

### ISSUE THREAD

**Issue by dum3ng** [f/vue-wait#83]
Just as the title said, the v1.4.6 in npm registry is still the old version, and lack of nuxt typescript support.

Release a new patch version could solve this, I thought.

**Comment by honzabilek4** [comment]
Exactly, I went to report here the same thing this. I think the author just forgot to bump the version when releasing the latest.

**Comment by honzabilek4** [comment]
@f do you have a minute to fix the published version on npm? If not, just let me know. I'll need to do a fork.

**Comment by f** [comment]
Hi @honzabilek4. Seems like I released a wrong build to the NPM. I've released a clean version and it's `1.4.8`

**Comment by f** [comment]
Please approve it's fixed and I'm going to close the task.

**Comment by honzabilek4** [comment]
Works well, thanks! 🎉
