### ISSUE TITLE
Failing on Server Side Rendering in Nuxt

### ISSUE THREAD

**Issue by appinteractive** [f/vue-wait#89]
<img width="498" alt="grafik" src="https://user-images.githubusercontent.com/432828/78356975-e1ba5380-75b0-11ea-8599-ab6a7b9a4bf5.png">

**Comment by JunjaK** [comment]
I Think this library only works client-side because It use dom element.  
So. you should use <client-only> tag in vue template code   
eg
```
<client-only>
  <v-wait/>
</client-only>
```

**Comment by JunjaK** [comment]
ref this page https://ko.nuxtjs.org/docs/2.x/features/nuxt-components/#the-client-only-component

**Comment by appinteractive** [comment]
Thanks for the reply, to be honest I do not remember if or how I fixed it as its over a year ago. I will close the ticket.
